# Generated by Django 5.0.7 on 2025-03-21 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('price', models.FloatField(verbose_name='Kitob narxi')),
                ('quantity', models.IntegerField(verbose_name='Kitob soni')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Kitob rasmi')),
                ('description', models.TextField(verbose_name='Kitob haqida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='reference nomi')),
                ('value', models.CharField(max_length=255, verbose_name='reference qiymati')),
            ],
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model nomi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Xaridor nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Sotib olingan miqdor')),
                ('total_price', models.FloatField(editable=False, verbose_name='Umumiy narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Xarid sanasi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_model', verbose_name='Kitob')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckripton', models.TextField(verbose_name='Tavsif')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_names', to='books.reference', verbose_name='Output nomi')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(verbose_name='Haqida')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sold_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_income', to='books.reference', verbose_name='Sotilgan kitob')),
            ],
        ),
        migrations.AddField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category_references', to='books.reference'),
        ),
        migrations.CreateModel(
            name='Cost_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Cost narxi')),
                ('quantity', models.IntegerField(verbose_name='Cost soni')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Cost rasmi')),
                ('description', models.TextField(verbose_name='Cost haqida')),
                ('creat_at', models.DateField(verbose_name='Cost sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.reference')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Cost_Models', to='books.somemodel', verbose_name='Cost nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism va familiya')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('experience', models.PositiveIntegerField(verbose_name='Tajriba (yil)')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Soatlik maosh')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hired_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.FloatField(verbose_name='tavsif')),
                ('price', models.FloatField(verbose_name='Ish narxi ')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Staff_work', to='books.staff', verbose_name='Xodim')),
            ],
        ),
    ]
