# Generated by Django 5.0.7 on 2025-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_model_is_deleted_cost_model_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Kitob soni'),
        ),
    ]
