# Generated by Django 5.0.7 on 2025-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_model_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
    ]
