# Generated by Django 5.0.7 on 2025-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_model',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
